export const NOTE_TYPES = {
  GET_NOTES: 'GET_NOTES',
  SET_NOTES: 'SET_NOTES',
  SET_IS_NOTES_LOADING: 'SET_IS_NOTES_LOADING',
  CREATE_NOTE: 'CREATE_NOTE',
  REMOVE_NOTE: 'REMOVE_NOTE',
  UPDATE_NOTE: 'UPDATE_NOTE',
};
